### ISSUE TITLE
Register on another Social media platform

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/social-media-verification#24]
Once twitter is established and tested it would be good to discuss another method of verification.
- Discord
- Telegram 
- other?

**Comment by fkondej** [comment]
This definitely possible. We would have to investigate what APIs are available for those Social Media.
i.e. research/spike each social media, what is doable and what we would like to achieve.

**Comment by campbellssource** [comment]
Although this does make sybil attacks quite a lot easier. I obviously have one twitter account and one discord account. I could use one to give money to the other.
it's probably almost as easy to have to twitter accounts.

I think we should discuss before implementation

**Comment by fkondej** [comment]
1. Discord
  - API docks: https://discord.com/developers/docs/intro
  - python library: https://discordpy.readthedocs.io/en/stable/
2. Telegram
  - API docks: https://core.telegram.org/
  - python library: a few options: https://core.telegram.org/bots/samples#python

**Comment by campbellssource** [comment]
We've also discussed the idea of doing something similar to step 1 on the token.vega.xyz/claim site (for an un-targeted code).
Given that the user will have to pay gas (twice) to claim their incentive why not make the first one a step that registered a Vega wallet too.

This may now work. Gas could be a disincentive to create a Sybil army, but on the other hand we'd want most incentives to be other more than the gas required to claim. 
Also, Barney mentioned he doesn't like the idea of having to pay to play

**Comment by fkondej** [comment]
won't do.
