### ISSUE TITLE
Add register date

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/social-media-verification#39]
It would be useful to have the date registered recorded and included in the `GET /parties` response.

This would make it easier for downstream scripts to add tokens for all parties registered more recently than a certain date.

## current output
```json5
[
  {
    "party_id": "01...ef",
    "twitter_handle": "___",
    "twitter_user_id": 123456789
  },
  // ...
]
```

## desired output
```json5
[
  {
    "party_id": "01...ef",
    "created": 1618474460,  // epoch seconds
    "last_modified": 1618474499,  // edit: let's have this too, also epoch seconds
    "twitter_handle": "___",
    "twitter_user_id": 123456789
  },
  // ...
]
```

**Comment by fkondej** [comment]
@ashleyvega we already collect this data and I want to confirm epoch format.
