### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/social-media-verification#6]
Add logging in the right format for Google Functions/Logging.

**Comment by fkondej** [comment]
Currently, important logs are logged in JSON format: one JSON in one line (no other data is logged in that line). This works great with GCP Log Explorer.
On top of that, there is `OneLog` helper annotation [see more](../blob/develop/src/services/onelog.py), that allows logging whole request/action information in a single line.
I was not able to use python's `logging` module, but `print` works.
